# Current used as scratch paper for python, but we can change this to show the rooms being generated

In [1]:
from Storage import Object, Room, Rotation

room = Room(800, 400, "Lab Room")
print(room)

Room | Width: 800, Height: 400, Number of Objects: 0
Objects: []


In [4]:
depth = 5
for j in range(-depth+1, 1):
    print(j)

-4
-3
-2
-1
0


In [7]:
from sympy import nextprime
print(nextprime(1))

2


In [17]:
import numpy as np
#a = np.random.rand(3, 3)
print(np.linalg.norm([3, 4]))


5.0


In [19]:
a = [(12, 2), (15, 3), (3, 5)]
a.sort()
print(a)
print(len(a))

[(3, 5), (12, 2), (15, 3)]
3


In [20]:
from random import randint
for i in range(10): 
    print(randint(0, 5))

4
4
4
4
1
1
5
1
0
3


In [31]:
import numpy as np
X = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
Y = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])**2
# print(xi)
# print(xj)
# print(np.sqrt((xi - xj)**2))
for xi, xj in zip([X], [Y]):
    print(xi)
    print(xj)
    print(np.sqrt((xi - xj)**2))

print(5*X - 2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[  1   4   9]
 [ 16  25  36]
 [ 49  64  81]
 [100 121 144]]
[[  0.   2.   6.]
 [ 12.  20.  30.]
 [ 42.  56.  72.]
 [ 90. 110. 132.]]
[[ 3  8 13]
 [18 23 28]
 [33 38 43]
 [48 53 58]]


In [3]:
from Storage import Rotation

if 1 == Rotation.RIGHT:
    print("Yes")

Yes


In [5]:
x, y = 4+2, 5+4
print(x, y)

6 9


In [2]:
from functools import reduce
import numpy as np

def _factorize(n: int) -> list[int]:
    """
    Returns the factors of n.
    :param n: int to factorize
    :return: list of factors
    """
    return set(reduce(list.__add__,([i, n//i] for i in range(1, int(n**0.5) + 1) if n % i == 0)))

a = _factorize(12)
print(a)

b = np.array([12, 4, 5])
c = np.where(b > 4)
print(b[c])
print([_factorize(x) for x in b[c]])

{1, 2, 3, 4, 6, 12}
[12  5]
[{1, 2, 3, 4, 6, 12}, {1, 5}]


In [7]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.sum(a))

45


In [12]:
width = 7
height = 5
euc_norm = 0 #euclidean norm of the room, used for the objective function
center = int(np.ceil(min(width, height)/2))
for i in range(center):
    if width < 2 or height < 2:
        euc_norm += center*width*height
    else:
        euc_norm += 2*(width + height - 2)*(i + 1)
        width -= 2
        height -= 2
print(euc_norm)

53


In [17]:
width = 100
height = 100
x = 50
y = 50
travel = min(x + 1, width - x, y + 1, height - y)
print(travel)

50


In [19]:
group = [1]
for g in group:
    print(g)
    if(g == 1):
        group.append(2)

1
2


In [50]:
a = np.ones((4,3))
b = np.ones((4,3))*3
a[1,2] = 0
a[3,2] = 0
print(a)

#loc = np.intersect1d(np.where(a[:,2] == 0), np.where(b[:,2] == 3))
loc = np.intersect1d(a[:,2] == 0, b[:,2] == 3)
# loc = np.where(a[:,2] == 0 and b[:,2] == 3)
print(loc)
a[loc,2] = 4
print(a)

[[1. 1. 1.]
 [1. 1. 0.]
 [1. 1. 1.]
 [1. 1. 0.]]
[ True]


IndexError: boolean index did not match indexed array along dimension 0; dimension is 4 but corresponding boolean dimension is 1

In [30]:
a = np.ones((100, 100), dtype=int)
a[10:20, 10:20] = 4
a[10:15, 10:15] = 3
b = np.where(a > 1)
print(b[0].shape)
c = np.transpose(np.where(a > 1))
# print(c.shape)
print(a[b])
d = np.unique(a[b])
print(d)
print(np.concatenate((d, [5])))

(100,)
[3 3 3 3 3 4 4 4 4 4 3 3 3 3 3 4 4 4 4 4 3 3 3 3 3 4 4 4 4 4 3 3 3 3 3 4 4
 4 4 4 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]
[3 4]
[3 4 5]


In [31]:
a = [np.array([1, 2, 3]), np.array([4, 5, 6]), np.array([7, 8])]
print([y for x in a for y in x])

[1, 2, 3, 4, 5, 6, 7, 8]


In [13]:
import numpy as np
a = np.random.randn(*(3, 3))
print(a)

b = np.array([1, 2, 3])
print(list(b))

[[-1.42056455  0.09090744  0.06434684]
 [-0.71761531 -1.44298366 -0.31430156]
 [-1.20828665 -0.38750311  0.87593241]]
[1, 2, 3]


In [23]:
a = np.array([1, 2, 3])
b = np.copy(a)
b[1] = 5
print(a)
print(b)

[1 2 3]
[1 5 3]


In [28]:
from collections import defaultdict


a = defaultdict(tuple)
a[1] = (1, 2)
a[2] = (3, 4)
a[3] = ()
a[4] = (5, 6)
print(a)

if 3 in a.keys():
    print("Yes")

defaultdict(<class 'tuple'>, {1: (1, 2), 2: (3, 4), 3: (), 4: (5, 6)})
Yes


In [40]:
b = np.array([1, 2, 3])
c = np.array([1, 2.1, 3.2])
a = [np.array_equal(b, c.astype(int)), np.array_equal(b, b)]
print(a.count(True) == len(a))
print(any(a))

True
True
