In [1]:
from Storage import Object, Room, Rotation

room = Room(800, 400, "Lab Room")
print(room)

Room | Width: 800, Height: 400, Number of Objects: 0
Objects: []


In [4]:
depth = 5
for j in range(-depth+1, 1):
    print(j)

-4
-3
-2
-1
0


In [7]:
from sympy import nextprime
print(nextprime(1))

2


In [17]:
import numpy as np
#a = np.random.rand(3, 3)
print(np.linalg.norm([3, 4]))


5.0


In [19]:
a = [(12, 2), (15, 3), (3, 5)]
a.sort()
print(a)
print(len(a))

[(3, 5), (12, 2), (15, 3)]
3


In [20]:
from random import randint
for i in range(10): 
    print(randint(0, 5))

4
4
4
4
1
1
5
1
0
3


In [31]:
import numpy as np
X = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
Y = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])**2
# print(xi)
# print(xj)
# print(np.sqrt((xi - xj)**2))
for xi, xj in zip([X], [Y]):
    print(xi)
    print(xj)
    print(np.sqrt((xi - xj)**2))

print(5*X - 2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[  1   4   9]
 [ 16  25  36]
 [ 49  64  81]
 [100 121 144]]
[[  0.   2.   6.]
 [ 12.  20.  30.]
 [ 42.  56.  72.]
 [ 90. 110. 132.]]
[[ 3  8 13]
 [18 23 28]
 [33 38 43]
 [48 53 58]]


In [3]:
from Storage import Rotation

if 1 == Rotation.RIGHT:
    print("Yes")

Yes


In [5]:
x, y = 4+2, 5+4
print(x, y)

6 9


In [17]:
from functools import reduce
import numpy as np

def _factorize(n: int) -> list[int]:
    """
    Returns the factors of n.
    :param n: int to factorize
    :return: list of factors
    """
    return set(reduce(list.__add__,([i, n//i] for i in range(1, int(n**0.5) + 1) if n % i == 0)))

a = _factorize(12)
print(a)

b = np.array([12, 4, 5])
c = np.where(b > 4)
print(b[c])
print([_factorize(x) for x in b[c]])

{1, 2, 3, 4, 6, 12}
[12  5]
[{1, 2, 3, 4, 6, 12}, {1, 5}]
